### ISSUE TITLE
Breeje - Missing deadline checks allow pending transactions to be maliciously executed

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#44]
Breeje

high

# Missing deadline checks allow pending transactions to be maliciously executed

## Summary

The `Periphery` contract does not allow users to submit a deadline for their action. This missing feature enables pending transactions to be maliciously executed at a later point.

## Vulnerability Detail

Here's how MEV Bot can exploit it without deadline check:

1. The swap transaction is pending in the mempool. The price of 1 token has gone up significantly since the transaction was signed, meaning Alice would receive a lot more second token when the swap is executed. But that also means that her minimum Output Amount value is outdated and would allow for significant slippage.
2. A MEV bot detects the pending transaction. Since the outdated minimum Output Amount now allows for high slippage, the bot sandwiches Alice, resulting in significant profit for the bot and significant loss for Alice.

This is the reason any critical functionality where user is going to interact with the pool should be passed with a deadline of execution. As pool balance and result out of interact with pool is time dependent, there should not be any attack vector left for attackers to manipulate. By setting deadline such attack vector will be mitigated.

## Impact

Loss of funds.

## Code Snippet

Functions which can be affected:

```solidity
File: Periphery.sol

178:    function swapForPTs(

204:    function swapForYTs(

240:    function swapPTs(

263:    function swapYTs(

275:    function swapYTsForTarget(

325:    function addLiquidity(

371:    function removeLiquidity(

```
[Link to Code](https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Periphery.sol#L178)

## Tool used

Manual Review

## Recommendation

Introduce a deadline parameter to the mentioned functions and add a require check at the end such that the transaction can go only when the deadline is not met.

Duplicate of #55

**Comment by Breeje16** [comment]
Escalate for 10 USDC

Firstly, It is a duplicate of #55 and Protocol team has already applied the Fix for this Issue considering it Valid. But Sometimes from past experience, even Confirmation from protocol is not enough to consider it as valid H/M issue. So here are my points on why it is valid issue as per Sherlock's Judging Criteria:

Here's the scenario of how the vulnerability can be exploited:

1. Alice made a call to any contract method where swapping is done let's say `addLiquidity`.
2. The transaction can be pending in mempool for a long time and the trading activity is very time sensitive. 
3. Having no deadline check, the trade transaction can be executed in a long time after the caller submit the transaction, at that time, the trade can be done in a sub-optimal price, which harms caller's position.
4. In this scenario, even slippage parameter won't completely rescue Alice. Let's say Alice wanted to restrict the slippage to 1% at today's exchange rate, results in `minAccepted` value of `x`. But in future, that `x` value can potentially lead to 20% slippage as the price has gone up for that token.
5. A MEV bot detects the pending transaction. Since the outdated maximum slippage value now allows for high slippage, the bot sandwiches Alice, resulting in significant profit for the bot and significant loss for Alice.

This is the Reason Uniswap uses deadline check for almost all the key interactions with the pool.

For Medium Issue:

> Medium: There is a viable scenario (even if unlikely) that could cause the protocol to enter a state where a material amount of funds can be lost. The attack path is possible with assumptions that either mimic on-chain conditions or reflect conditions that have a reasonable chance of becoming true in the future. The more expensive the attack is for an attacker, the less likely it will be included as a Medium (holding all other factors constant). The vulnerability must be something that is not considered an acceptable risk by a reasonable protocol team.

Above is a valid scenario that could cause the protocol to enter a state where a material amount of funds can be lost. In the fix that Protocol did, Now any transaction which is executed after 4 hours from signing, will be reverted. This way they have successfully mitigated this attack vector. As Protocol team are applying this Fix, it is also not an acceptable risk from their side.

Also as per Sherlock Docs: 

> Slippage related issues showing a definite loss of funds with a detailed explanation for the same can be considered valid high

The scenario I showed can result in Slippage related Issue. That's why I marked it High. High or Medium is upto you to decide, But Definitely it's a Valid Issue as per Sherlock Validity Criteria.

**Comment by hrishibhat** [comment]
Escalation rejected

Given that the slippage parameters are in place resulting in users getting what is expected. Adding a deadline check is just additional protection from the above scenario which does not warrant for a valid high/medium. 
Considering this issue a low
