### ISSUE TITLE
tsvetanovv - Solmate's SafeTransferLib doesn't check whether the ERC20 contract exists

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-sense-judging#51]
tsvetanovv

medium

# Solmate's SafeTransferLib doesn't check whether the ERC20 contract exists

## Summary
The `safeTransfer` and `safeTransferFrom` don't check the existence of code at the token address. 

## Vulnerability Detail
This may lead to miscalculation of funds and may lead to loss of funds, because if `safeTransfer()` and `safeTransferFrom()` are called on a token address that doesn't have a contract in it, it will always return success, bypassing the return value check.

## Impact
Due to this protocol will think that funds have been transferred successfully, and records will be accordingly calculated, but in reality, funds were never transferred. So this will lead to miscalculation and possibly loss of funds.

## Code Snippet

```solidity
https://github.com/sherlock-audit/2023-03-sense/blob/main/sense-v1/pkg/core/src/Divider.sol#L7
import { SafeTransferLib } from "solmate/utils/SafeTransferLib.sol";
```

## Tool used

Manual Review

## Recommendation

Use Openzeppelin's safeERC20 or implement a code existence check.

**Comment by jparklev** [comment]
Disputed: transfer() and transferFrom() will fail if the addition/subtraction cannot be performed, causing a revert on that contract and therefore in the whole transaction

**Comment by sayan0111** [comment]
Escalate for 10 USDC.

The problem that's mentioned here is related to using `safeTransfer` & `safeTransferFrom` of `solmate` .
this may lead to miscalculation of funds and may lead to loss of funds, because if `safeTransfer()` and `safeTransferFrom()` are called on a token address that doesn't have a contract in it, it will always return success, bypassing the return value check. Due to this protocol will think that funds have been transferred successfully, and records will be accordingly calculated, but in reality, funds were never transferred.(check https://github.com/sherlock-audit/2023-03-sense-judging/issues/22 for detailed explanation).
The team stated that
>> "transfer() and transferFrom() will fail if the addition/subtraction cannot be performed, causing a revert on that contract and therefore in the whole transaction"
>>
but I noticed lack of checks to make sure that the transfers fails if addition/subtraction cannot be performed in several instances where `safeTransfer` or `safeTransferFrom` is used.

https://github.com/sense-finance/sense-v1/blob/82abac25404d83b7aefaaeb46631f1d050dc4a4e/pkg/core/src/Periphery.sol#L225

https://github.com/sense-finance/sense-v1/blob/82abac25404d83b7aefaaeb46631f1d050dc4a4e/pkg/core/src/Periphery.sol#L645

https://github.com/sense-finance/sense-v1/blob/82abac25404d83b7aefaaeb46631f1d050dc4a4e/pkg/core/src/Periphery.sol#L1013

https://github.com/sense-finance/sense-v1/blob/82abac25404d83b7aefaaeb46631f1d050dc4a4e/pkg/core/src/Divider.sol#L249

For reference,here are some instances where this issue was considered valid under almost similar conditions,in other audit  contests
https://github.com/sherlock-audit/2022-11-bond-judging/issues/8
https://github.com/code-423n4/2022-08-olympus-findings/issues/117

**Comment by spyrosonic10** [comment]
Escalate for 10 USDC

This is not an issue in this project.  All places where safeTransfer and safeTransferFrom is used in this project, it has some additional method call on same asset for example it calls balanceOf() method on the asset. If address is not contract then it will fail due to balanceOf() call.  Most of the assets are trusted and confirmed ERC20 contract.  This is invalid issue.

**Comment by fedealconada** [comment]
> Escalate for 10 USDC
> 
> This is not an issue in this project. All places where safeTransfer and safeTransferFrom is used in this project, it has some additional method call on same asset for example it calls balanceOf() method on the asset. If address is not contract then it will fail due to balanceOf() call. Most of the assets are trusted and confirmed ERC20 contract. This is invalid issue.

Our previous answer was wrong. As you pointed out, Solmate's `safeTransfer1 and 1safeTransferFrom` do not check the contract size. BUT, I believe this won't have any impact whatsoever since:
- if these functions are used with target, we know for sure this contracts have code because we are the ones that have created the adapters
- if these functions are used when transferring tokens that have been used to zap, then te tx would have already failed when doing the zap via 0x
- if we are in a permissionless mode, yes, the issue could have an impact but as one could also be onboarding malicious adapters of any kind, this woudl be expected and it is the user's responsbility to use "non-verified by sense" adapters
